name: your_printer
description: "Thermal printer app - Your Printer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  esc_pos_utils: ^1.1.0
  flutter_blue_plus: ^1.35.3
  network_info_plus: ^6.1.2
  file_picker: ^8.1.7
  image: ^3.3.0
  image_cropper: ^8.1.0
  path_provider: ^2.1.5
  usb_serial: ^0.5.1
  pdfx: ^2.9.2
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
